# Generated by Django 5.1 on 2024-08-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='k_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('call_type', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=20)),
                ('imsi', models.CharField(max_length=100)),
                ('b_party_msisdn', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('calling_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('imei', models.CharField(max_length=100)),
                ('call_location', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='a_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_report', models.CharField(max_length=255)),
                ('caller_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('third_party_number', models.CharField(blank=True, max_length=20, null=True)),
                ('call_initial_time', models.DateTimeField()),
                ('conversation_duration', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('charged_mobile_user_imei', models.CharField(max_length=100)),
                ('charged_mobile_user_imsi', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('site_id', models.CharField(max_length=100)),
                ('cgi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='z_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('call_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('calling_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('call_location', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('split', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
