# Generated by Django 5.1 on 2024-08-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('T', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=255)),
                ('name_info', models.CharField(max_length=255)),
                ('bookid', models.CharField(max_length=255)),
                ('app_book_date', models.DateTimeField()),
                ('received_from', models.CharField(max_length=255)),
                ('accused_char', models.CharField(max_length=255)),
                ('app_form', models.CharField(max_length=255)),
                ('app_date', models.DateTimeField()),
                ('period_fromto', models.CharField(max_length=255)),
                ('tech_name', models.CharField(max_length=255)),
                ('app_kind', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('T', models.AutoField(primary_key=True, serialize=False)),
                ('name_accused', models.CharField(max_length=255)),
                ('saved_numbers', models.CharField(max_length=255)),
                ('saved_name', models.CharField(max_length=255)),
                ('saved_info', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='KTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATETIME', models.DateTimeField()),
                ('CALL_TYPE', models.CharField(max_length=255)),
                ('MSISDN', models.CharField(max_length=255)),
                ('IMSI', models.CharField(max_length=255)),
                ('B_PARTY_MSISDN', models.CharField(max_length=255)),
                ('DURATION', models.IntegerField()),
                ('CALLINGNUMBER', models.CharField(max_length=255)),
                ('CALLEDNUMBER', models.CharField(max_length=255)),
                ('IMEI', models.CharField(max_length=255)),
                ('CALLLOCATION', models.CharField(max_length=255)),
                ('SITE_ID', models.CharField(max_length=255)),
                ('SITE', models.CharField(max_length=255)),
                ('GOVERNORATE', models.CharField(max_length=255)),
                ('LONGITUDE', models.FloatField()),
                ('LATITUDE', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_temp', to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ATemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_REPORT', models.CharField(max_length=255)),
                ('CALLER_NUMBER', models.CharField(max_length=255)),
                ('CALLED_NUMBER', models.CharField(max_length=255)),
                ('THIRD_PARTY_NUMBER', models.CharField(default='UNKNOWN', max_length=255)),
                ('CALL_INITIAL_TIME', models.DateTimeField()),
                ('CONVERSATION_DURATION', models.IntegerField()),
                ('CITY', models.CharField(max_length=255)),
                ('SITE_NAME', models.CharField(max_length=255)),
                ('CHARGED_MOBILE_USER_IMEI', models.CharField(max_length=255)),
                ('CHARGED_MOBILE_USER_IMSI', models.CharField(max_length=255)),
                ('LON', models.FloatField()),
                ('LAT', models.FloatField()),
                ('SITE_ID', models.CharField(max_length=255)),
                ('CGI', models.CharField(max_length=255)),
                ('COMMENTS', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_temp', to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ZTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('CALL_TYPE', models.CharField(max_length=255)),
                ('Duration', models.IntegerField()),
                ('Calling_Number', models.CharField(max_length=255)),
                ('Called_Number', models.CharField(max_length=255)),
                ('Call_Location', models.CharField(max_length=255)),
                ('Site_ID', models.CharField(max_length=255)),
                ('Split', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_temp', to='app.person')),
            ],
        ),
    ]
